@host = http://localhost:8080
@basicAuth = aG91c2U6aG91c2UxMjM=
@enfIdDiabetes = 11111111-1111-1111-1111-111111111111
@enfIdHipertension = 22222222-2222-2222-2222-222222222222
@sinIdTos = aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1
@sinIdDolorCabeza = bbbbbbb2-bbbb-bbbb-bbbb-bbbbbbbbbbb2

### 0) Ping (abierto)
GET {{host}}/api/ping

### 1) Listar enfermedades
GET {{host}}/api/enfermedades
Authorization: Basic {{basicAuth}}

### 2) Listar síntomas
GET {{host}}/api/sintomas
Authorization: Basic {{basicAuth}}

### 3) Vincular Tos a Diabetes (201 nuevo, 204 si ya existe)
POST {{host}}/api/enfermedades/{{enfIdDiabetes}}/sintomas/{{sinIdTos}}
Authorization: Basic {{basicAuth}}

### 4) Reintentar vinculación (idempotente → 204)
POST {{host}}/api/enfermedades/{{enfIdDiabetes}}/sintomas/{{sinIdTos}}
Authorization: Basic {{basicAuth}}

### 5) Listar síntomas de Diabetes tipo 2
GET {{host}}/api/enfermedades/{{enfIdDiabetes}}/sintomas
Authorization: Basic {{basicAuth}}

### 6) Detalle de Diabetes tipo 2
GET {{host}}/api/enfermedades/{{enfIdDiabetes}}
Authorization: Basic {{basicAuth}}

### 7) Detalle de Tos
GET {{host}}/api/sintomas/{{sinIdTos}}
Authorization: Basic {{basicAuth}}
