server.port=8080
spring.application.name=vitalmas

# PostgreSQL (Configurado para el puerto 5433 de Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/vitalmas?sslmode=disable
spring.datasource.username=vitalmas
spring.datasource.password=vitalmas
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logs de errores completos (Entorno de desarrollo)
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# JWT
security.jwt.secret=SECURITY_JWT_SECRET_REMOVED
security.jwt.expiration-seconds=3600 