server.port=8080
spring.application.name=vitalmas

# PostgreSQL (Configurado para el puerto 5433 de Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/vitalmas?sslmode=disable
spring.datasource.username=vitalmas
spring.datasource.password=vitalmas
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL init
spring.sql.init.mode=always

# Logs de errores completos (Entorno de desarrollo)
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# JWT
security.jwt.secret=9F4C2A61E7C8B3D0A52D1F9C8E7A6D4F1A9B7E3C5F8D2A6C1B4E7D9F2C6A8B1
security.jwt.expiration-seconds=3600